/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : AttendanceStatus,
  'studentName' : IDL.Text,
  'date' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func([IDL.Text, IDL.Text, AttendanceStatus], [IDL.Nat], []),
  'deleteRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'updateStatus' : IDL.Func([IDL.Nat, AttendanceStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : AttendanceStatus,
    'studentName' : IDL.Text,
    'date' : IDL.Text,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [IDL.Text, IDL.Text, AttendanceStatus],
        [IDL.Nat],
        [],
      ),
    'deleteRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'updateStatus' : IDL.Func([IDL.Nat, AttendanceStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };